### PR TITLE
Fix byte order in TOTMR register

### LINKED ISSUE #123: SPI assertion with W5500 on same bus as LCD devices (IDFGH-16779)
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Not raise an assertion

### Actual behavior (suspected bug)

assert failed: spi_hal_setup_trans /IDF/components/hal/spi_hal_iram.c:134 (spi_ll_get_running_cmd(hw) == 0)

Backtrace: 0x4037b9a9:0x3fcc0f80 0x4037b971:0x3fcc0fa0 0x40384309:0x3fcc0fc0 0x403823f3:0x3fcc10e0 0x40378e2a:0x3fcc1110 0x4037927b:0x3fcc1160 0x40379346:0x3fcc11a0 0x4202b797:0x3fcc11c0 0x420c156b:0x3fcc1220 0x4202b0d7:0x3fcc1240 0x4037c689:0x3fcc1280
--- 0x4037b9a9: panic_abort at /Users/jeremy/esp/esp-idf/components/esp_system/panic.c:469
--- 0x4037b971: esp_system_abort at /Users/jeremy/esp/esp-idf/components/esp_system/port/esp_system_chip.c:87
--- 0x40384309: __assert_func at /Users/jeremy/esp/esp-idf/components/newlib/src/assert.c:80
--- 0x403823f3: spi_hal_setup_trans at /Users/jeremy/esp/esp-idf/components/hal/spi_hal_iram.c:134
--- 0x40378e2a: spi_new_trans at /Users/jeremy/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:832
--- 0x4037927b: spi_device_polling_start at /Users/jeremy/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:1442
--- 0x40379346: spi_device_polling_transmit at /Users/jeremy/esp/esp-idf/components/esp_driver_spi/src/gpspi/spi_master.c:1497
--- 0x4202b797: w5500_spi_read at /Users/jeremy/esp/esp-idf/components/esp_eth/src/spi/w5500/esp_eth_mac_w5500.c:165
--- 0x420c156b: w5500_read at /Users/jeremy/esp/esp-idf/components/esp_eth/src/spi/w5500/esp_eth_mac_w5500.c:185
--- 0x4202b0d7: emac_w5500_task at /Users/jeremy/esp/esp-idf/components/esp_eth/src/spi/w5500/esp_eth_mac_w5500.c:835
--- 0x4037c689: vPortTaskWrapper at /Users/jeremy/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:139

### Error logs or terminal output

```shell

```

### Steps to reproduce the behavior

Application on M5Stack CoreS3 using PoE LAN Base which is W5500 based

### Project release version

ESP-IDF v5.5.1

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

MacOS

### Operating system version

Tahoe

### Shell

ZSH

### Additional context

Originally reported against ESP-IDF v5.5.1 here: https://github.com/espressif/esp-idf/issues/17860

Wondering if this is due to contention between the W5500 driver and the LCD driver when the two devices are on the same bus.

### PR DESCRIPTION
**Pull request by bogdankolendovskyy**
Commit fixes the byte order in the struct that defines TOTMR register and adds padding to prevent possible issues among compilers. Also addresses two typos made in custom_ioctl commands.

Closes https://github.com/espressif/esp-eth-drivers/issues/48

## Description
Fix byte order in `lan867x_plca_totmr_reg_t` and add padding to `lan867x_plca_***_reg_t` structs to prevent possible undefined behaviour. Fix typos in `custom_ioctl` commands
```diff
--- LAN867x_ETH_CMD_S_PLCA_TOT
+++ LAN867X_ETH_CMD_S_PLCA_TOT
```
and
```diff
--- LAN867x_ETH_CMD_G_PLCA_TOT
+++ LAN867X_ETH_CMD_G_PLCA_TOT
```

## Testing

---

## Checklist

Before submitting a Pull Request, please ensure the following:

- [ ] 🚨 This PR does not introduce breaking changes.
- [x] All CI checks (GH Actions) pass.
- [x] Documentation is updated as needed.
- [x] Tests are updated or added as necessary.
- [x] Code is well-commented, especially in complex areas.
- [x] Git history is clean — commits are squashed to the minimum necessary.

### CODE REVIEW

**Review by kostaond — APPROVED** [review]

File: lan867x/src/esp_eth_phy_lan867x.c [hunk 1]
```diff
@@ -47,33 +47,37 @@ typedef union {
...
     uint32_t val;
 } lan867x_plca_totmr_reg_t;
 #define ETH_PHY_PLCA_TOTMR_REG_MMD_ADDR (0xCA04)
 
 typedef union {
     struct {
-        uint8_t maxbc;  // Maximum burst count
-        uint8_t btmr;   // Burst timer
+        uint8_t maxbc;      // Maximum burst count
+        uint8_t btmr;       // Burst timer
```
Comment (kostaond) [inline lan867x/src/esp_eth_phy_lan867x.c:79]: Shouldn't be also swapped?

Comment (bogdankolendovskyy) [reply lan867x/src/esp_eth_phy_lan867x.c]: Thanks for pointing that out, yes they do.

**Review by kostaond — APPROVED** [review]
